# Generated by Django 4.2.25 on 2025-11-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Например 'мы' или 'гарантируем'",
                        max_length=200,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Основная цифра/процент/текст, например '50%' или '1'",
                        max_length=200,
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Нижняя строка, например 'на рынке' или 'безопасность'",
                        max_length=200,
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Преимущество",
                "verbose_name_plural": "Преимущества",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "url",
                    models.CharField(
                        blank=True, help_text="URL или internal path", max_length=500
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Пункт меню",
                "verbose_name_plural": "Пункты меню",
                "ordering": ["order"],
            },
        ),
    ]
